// packages/create-plugin/templates/svelte-custom-dashboard/src/components/Dashboard.svelte
<script lang="ts">
  import "@frc-web-components/fwc/components";
  import { getEntry } from "@frc-web-components/svelte";
  import MyElement from "./MyElement.svelte";

  let toggled = getEntry(`/dashboard/toggled`, false);
  let pose = getEntry(`/SmartDashboard/Field/Robot`, [0, 0, 0]);
  let count = getEntry(`/dashboard/count`, 0);

  const updateToggle = () => {
    toggled.setValue(!$toggled);
  };
</script>

<div>
  <frc-sendable-chooser
    source-key="/Shuffleboard/Autonomous/SendableChooser[0]"
  />
  <frc-basic-fms-info source-key="/FMSInfo" />
  <frc-toggle-button
    label="Toggle Button"
    toggled={$toggled}
    on:toggle={updateToggle}
  />
  <MyElement count={$count} onIncrement={(value) => count.setValue(value)} />
</div>
<frc-field crop-left=".1" crop-right=".9" rotation-unit="deg">
  <frc-field-robot color="blue" opacity="1" pose={$pose}></frc-field-robot>
</frc-field>

<style>
  div {
    display: flex;
    gap: 15px;
    align-items: start;
  }

  frc-field {
    width: 500px;
    height: 300px;
  }
</style>

// packages/create-plugin/templates/react-custom-dashboard/src/components/Dashboard.tsx
import {
  useEntry,
  BasicFmsInfo,
  SendableChooser,
  ToggleButton,
  Field,
  FieldRobot,
} from '@frc-web-components/react';
import MyElement from './MyElement';
import { CSSProperties } from 'react';

const Dashboard = () => {
  const [toggled, setToggled] = useEntry('/dashboard/toggled', false);
  const [pose] = useEntry('/SmartDashboard/Field/Robot', [0, 0, 0]);
  const [count, setCount] = useEntry('/dashboard/count', 0);

  const updateToggle = () => {
    setToggled(!toggled);
  };

  const divStyles: CSSProperties = {
    display: 'flex',
    gap: '15px',
    alignItems: 'start',
  };

  const fieldStyles: CSSProperties = {
    width: '500px',
    height: '300px',
  };

  return (
    <>
      <div style={divStyles}>
        <SendableChooser source-key="/Shuffleboard/Autonomous/SendableChooser[0]" />
        <BasicFmsInfo source-key="/FMSInfo" />
        <ToggleButton
          label="Toggle Button"
          toggled={toggled}
          ontoggle={updateToggle}
        />
        <MyElement count={count} onIncrement={(value) => setCount(value)} />
      </div>
      <Field
        style={fieldStyles}
        cropLeft={0.1}
        cropRight={0.9}
        rotationUnit="deg"
      >
        <FieldRobot color="blue" opacity={1} pose={pose} />
      </Field>
    </>
  );
};

export default Dashboard;
