// examples/example-svelte-plugin/src/MyElement.svelte
<svelte:options customElement="my-svelte-element" />

<script lang="ts">
  import { getAssetUrl } from  '@frc-web-components/app';
  export let count: number = 0;
  const increment = () => {
    count += 1;
  };
</script>

<button on:click={increment}>
  <img src={getAssetUrl('party.svg')} alt="party time" />
  Party Guests: {count}
</button>

<style>
  button {
    padding: 8px;
    display: inline-flex;
    align-items: center;
    gap: 8px;
  }
</style>

// packages/create-plugin/templates/react/src/MyElement.tsx
import { useEffect, useState, CSSProperties } from "react";
import r2wc from "@r2wc/react-to-web-component";
import { getAssetUrl } from "@frc-web-components/app";

function MyElement({ count }: { count: number }) {
  const [currentCount, setCount] = useState(0);

  useEffect(() => {
    setCount(count);
  }, [count]);

  const styles: CSSProperties = {
    padding: "8px",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
  };

  return (
    <button
      style={styles}
      onClick={() => {
        setCount(currentCount + 1);
      }}
    >
      <img src={getAssetUrl("party.svg")} alt="party time" />
      Party Gusts: {currentCount}
    </button>
  );
}

const WebApp = r2wc(MyElement, {
  props: {
    count: "number",
  },
});

customElements.define("my-react-element", WebApp);

export default MyElement;
